spring.application.name=sewerverdict
spring.thymeleaf.cache=false
server.error.whitelabel.enabled=false

app.storage.root=storage
app.review-date=2026-03-17
app.contact-email=contact@sewerverdict.com
